import { Box, Container, Heading } from "@chakra-ui/layout";
import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Concept XYZ - Add Digits</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Box as="main" bgColor="#ddd">
				<Container bgColor="white" minHeight="100vh" p={4}>
					<Heading>Select Digits to create a sum</Heading>
				</Container>
			</Box>
		</>
	);
}
